name: Build Nebula Ultra APK
on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      # 1. Очистка и создание SWAP (Исправленный метод)
      - name: Free Disk Space and Setup Swap
        run: |
          # Удаляем мусор
          sudo rm -rf /usr/share/dotnet /opt/ghc "/usr/local/share/boost" "$AGENT_TOOLSDIRECTORY"
          
          # Вместо перезаписи системного /swapfile, создаем свой в /mnt (там больше места)
          sudo swapoff -a
          sudo dd if=/dev/zero of=/mnt/nebula_swap bs=1M count=12288
          sudo chmod 600 /mnt/nebula_swap
          sudo mkswap /mnt/nebula_swap
          sudo swapon /mnt/nebula_swap
          
          free -h

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'

      - name: Install System Dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y build-essential libsqlite3-dev lld python3-dev libffi-dev libssl-dev
          pip install --upgrade pip
          pip install "Cython<3.0.0" wheel virtualenv buildozer

      - name: Build with Buildozer
        run: |
          export PATH=$PATH:~/.local/bin
          # Ограничиваем аппетит Java
          export GRADLE_OPTS="-Xmx4g -Dorg.gradle.daemon=false -Dorg.gradle.workers.max=1"
          # Принимаем лицензии
          yes | buildozer -v android debug
        env:
          BUILDOZER_ALLOW_ORG_NAME_START: 1

      - name: Upload APK
        uses: actions/upload-artifact@v4
        with:
          name: Nebula-Ultra-Release
          path: bin/*.apk
          
