name: Build Android APK
on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Build APK with Buildozer
        uses: ArtemSerebryakov/buildozer-action@v1
        with:
          buildozer_version: master
          command: android debug
          # Сборка ИИ библиотек занимает много времени, GitHub дает 6 часов.
          
      - name: Upload Artifact
        uses: actions/upload-artifact@v2
        with:
          name: NebulaAI-Pobeda-APK
          path: bin/*.apk
          
