name: Build Nebula Ultimate
on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v4
      - name: Setup JDK 17
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'temurin'

      - name: Clean Space
        run: |
          sudo rm -rf /usr/share/dotnet /opt/ghc "/usr/local/share/boost"
          sudo docker image prune -af

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'

      - name: Install Buildozer
        run: |
          pip install --upgrade pip
          pip install "Cython<3.0.0" wheel virtualenv buildozer

      - name: Build APK (Smart Clean Fix)
        run: |
          export PATH=$PATH:~/.local/bin
          export GRADLE_OPTS="-Xmx6g -Dorg.gradle.daemon=false"
          
          # ФИКС ОШИБКИ: Чистим только если есть что чистить
          if [ -d ".buildozer/android/platform/python-for-android" ]; then
            buildozer android clean
          fi
          
          yes | buildozer -v android debug
        env:
          BUILDOZER_ALLOW_ORG_NAME_START: 1

      - name: Upload APK
        uses: actions/upload-artifact@v4
        with:
          name: Nebula-V8-Final
          path: bin/*.apk
          
